/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget

/administration/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

/administration/users:
  controller: admin
  action: users

/administration/projects:
  controller: admin
  action: projects

/administration/projects/add:
  controller: project
  action: add

/administration/projects/delete:
  controller: project
  action: delete


/administration/concerts:
  controller: admin
  action: concerts

/administration/concerts/add:
  controller: concert
  action: add

/administration/templates:
  controller: admin
  action: templates

/mail:
  controller: myMail
  action: testMail

/testsam:
  controller: testSam
  action: test

/administration/newsletter:
  controller: newsletter
  action: list
  security:
    - admin

/administration/newsletter/add:
  controller: newsletter
  action: add
  security:
    - admin

/administration/newsletter/edit/{idnews}:
  controller: newsletter
  action: edit
  param:
    - idnews
  security:
    - admin

/administration/newsletter/subscribeuser/{iduser}/{idnews}:
  controller: newsletter
  action: subscribe
  param:
    - iduser
    - idnews
  security:
    - admin

/administration/newsletter/unsubscribeuser/{iduser}/{idnews}:
  controller: newsletter
  action: unsubscribe
  param:
    - iduser
    - idnews
  security:
    - admin

/administration/newsletter/send/{idnews}:
  controller: newsletter
  action: send
  param:
   - idnews
  security:
    - admin

/administration/newsletter/delete/{idnews}:
  controller: newsletter
  action: delete
  param:
   - idnews
  security:
    - admin

/administration/media:
  controller: project
  action: list
  security:
    - admin

/administration/newsletter/test/{idnews}/{iduser}:
  controller: newsletter
  action: test
  param: 
    - idnews
    - iduser
  security:
    - admin