/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget

/administration/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

/administration/users:
  controller: admin
  action: users

/administration/projects:
  controller: admin
  action: projects

/administration/projects/add:
  controller: project
  action: add

/administration/projects/delete:
  controller: project
  action: delete


/administration/concerts:
  controller: admin
  action: concerts

/administration/concerts/add:
  controller: concert
  action: add

/administration/templates:
  controller: admin
  action: templates

/mail:
  controller: myMail
  action: testMail

/testsam:
  controller: testSam
  action: test

/administration/newsletter:
  controller: newsletter
  action: list
  security:
    - admin

/administration/newsletter/add:
  controller: newsletter
  action: add
  security:
    - admin

/administration/newsletter/edit:
  controller: newsletter
  action: edit
  security:
    - admin

/administration/newsletter/subscribeuser:
  controller: newsletter
  action: subscribe
  security:
    - admin

/administration/newsletter/unsubscribeuser:
  controller: newsletter
  action: unsubscribe
  security:
    - admin

# /page/{nompage}/: 
#   controller: testSam
#   action: test
#   parameters: {nompage}